// GET action types
export const FETCH_SINGLE_WORKOUT = "FETCH_SINGLE_WORKOUT";
export const FETCH_ALL_WORKOUTS = "FETCH_ALL_WORKOUTS";
// export const FETCH_ALL_WORKOUTS_SUCCESS = "FETCH_ALL_WORKOUTS_SUCCESS";
// export const FETCH_ALL_WORKOUTS_FAIL = "FETCH_ALL_WORKOUTS_FAIL";
// POST action types
export const CREATE_WORKOUT = "CREATE_WORKOUT";
// export const CREATE_WORKOUT_SUCCESS = "CREATE_WORKOUT_REQUEST";
// export const CREATE_WORKOUT_FAIL = "CREATE_WORKOUT_REQUEST";
export const UPDATE_WORKOUT = "UPDATE_WORKOUT";
export const DELETE_WORKOUT = "DELETE_WORKOUT";
export const LOADING = "LOADING";
export const NOT_LOADING = "NOT_LOADING";
