// GET action types
export const FETCH_ALL_WORKOUTS = "FETCH_ALL_WORKOUTS";
// export const FETCH_ALL_WORKOUTS_SUCCESS = "FETCH_ALL_WORKOUTS_SUCCESS";
// export const FETCH_ALL_WORKOUTS_FAIL = "FETCH_ALL_WORKOUTS_FAIL";
// POST action types
export const CREATE_WORKOUT = "CREATE_WORKOUT";
// export const CREATE_WORKOUT_SUCCESS = "CREATE_WORKOUT_REQUEST";
// export const CREATE_WORKOUT_FAIL = "CREATE_WORKOUT_REQUEST";
